/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JCAdapter */

#ifndef _Included_JCAdapter
#define _Included_JCAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JCAdapter
 * Method:    interpolateC
 * Signature: (LConfiguration;[B)V
 */
JNIEXPORT void JNICALL Java_com_xoomcode_acidmaps_adapter_JCAdapter_interpolateC(JNIEnv *, jobject, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
