.TH "AcidMaps::Configuration" 3 "Tue Nov 2 2010" "Version 2.0.0" "libams" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AcidMaps::Configuration \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <configuration.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBoutput_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file configuration.h.
.SH "Member Data Documentation"
.PP 
.SS "int \fBAcidMaps::Configuration::output_length\fP"
.PP
Definition at line 13 of file configuration.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libams from the source code.
