.TH "acid_maps::Configuration" 3 "Tue Nov 2 2010" "Version 2.0.0" "libacid-maps" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acid_maps::Configuration \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <configuration.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBoutput_buffer_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTodo\fP
.RS 4
Brief and description 
.RE
.PP

.PP
Definition at line 21 of file configuration.h.
.SH "Member Data Documentation"
.PP 
.SS "int \fBacid_maps::Configuration::output_buffer_length\fP"
.PP
Definition at line 22 of file configuration.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libacid-maps from the source code.
