.TH "AcidMaps" 3 "Tue Nov 2 2010" "Version 2.0.0" "libams" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AcidMaps \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBConfiguration\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinterpolate\fP (\fBConfiguration\fP cfg, char *out)"
.br
.RI "\fIGenerates an interpolated image with the given configuration. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void AcidMaps::interpolate (Configuration cfg, char * out)"
.PP
Generates an interpolated image with the given configuration. Aca te cuento q hace, como xq cosas asi viste
.PP
\fBParameters:\fP
.RS 4
\fIcfg\fP \fBConfiguration\fP lalala
.br
\fIout\fP char* mas cosas
.RE
.PP
\fBTodo\fP
.RS 4
More documentation 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libams from the source code.
