.TH "acid_maps" 3 "Tue Nov 2 2010" "Version 2.0.0" "libacid-maps" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acid_maps \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBConfiguration\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinterpolate\fP (\fBConfiguration\fP configuration, char *output_buffer)"
.br
.RI "\fIGenerates an interpolated raster with the given configuration. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void acid_maps::interpolate (Configuration configuration, char * output_buffer)"
.PP
Generates an interpolated raster with the given configuration. \fBParameters:\fP
.RS 4
\fIconfiguration\fP \fBConfiguration\fP 
.br
\fIoutput_buffer\fP char*
.RE
.PP
\fBTodo\fP
.RS 4
More documentation 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libacid-maps from the source code.
