.TH "source/ams.cc" 3 "Tue Nov 2 2010" "Version 2.0.0" "libams" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/ams.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ams.h'\fP
.br
\fC#include 'configuration.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAcidMaps\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAcidMaps::interpolate\fP (Configuration cfg, char *out)"
.br
.RI "\fIGenerates an interpolated image with the given configuration. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libams from the source code.
