.TH "source/ams.h" 3 "Tue Nov 2 2010" "Version 2.0.0" "libams" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/ams.h \- 
.PP
Acid Maps library main header.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAcidMaps\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAcidMaps::interpolate\fP (Configuration cfg, char *out)"
.br
.RI "\fIGenerates an interpolated image with the given configuration. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Acid Maps library main header. 

Some details Lalal allala lala
.PP
\fBVersion:\fP
.RS 4
2.0.0 
.RE
.PP
\fBAuthor:\fP
.RS 4
Fabio R. Panettieri 
.RE
.PP
\fBDate:\fP
.RS 4
2010-11-02 
.RE
.PP
\fBNote:\fP
.RS 4
no para  si 
.RE
.PP

.PP
Definition in file \fBams.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libams from the source code.
