.TH "source/configuration.h" 3 "Tue Nov 2 2010" "Version 2.0.0" "libacid-maps" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/configuration.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBacid_maps::Configuration\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBacid_maps\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDate:\fP
.RS 4
2010-11-02 
.RE
.PP
\fBAuthors:\fP
.RS 4
Fabio R. Panettieri
.RE
.PP
\fBTodo\fP
.RS 4
Brief and description
.RE
.PP

.PP
Definition in file \fBconfiguration.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libacid-maps from the source code.
